# Generated by Django 4.1.7 on 2023-03-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexapi', '0003_user_phrase_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='indexapi.user'),
        ),
    ]
