# Generated by Django 4.1.7 on 2023-03-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indxapp', '0002_users_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
